x-configuration: &CONFIGURATION
  volumes:
    - .:/Source:ro
  working_dir: /Build
  command: cat /etc/os-release

services:

  ubuntu:
    image: clxssy/ubuntu
    <<: *CONFIGURATION

  fedora:
    image: clxssy/fedora
    <<: *CONFIGURATION

