services:

  ubuntu:
    image: clxssy/ubuntu
    volumes: 
      - .:/Source:ro
    working_dir: /Build
    command: cat /etc/os-release

  fedora:
    image: clxssy/fedora
    volumes: 
      - .:/Source:ro
    working_dir: /Build
    command: cat /etc/os-release

